# define list
{{- $myList := list 1 2 3 4 5 }}

# append item
{{- $myList = append $myList 6 }}

{{- range $myList }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "serviceAccount-%d" . }}
{{- end }}

{{- /*
##### output #####
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: serviceAccount-1
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: serviceAccount-2
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: serviceAccount-3
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: serviceAccount-4
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: serviceAccount-5
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: serviceAccount-6
*/ -}}